spring.jdbc.template.query-timeout: 10m



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zarnicms
    username: zarnicms_zarni
    password: zarnicms_zarni_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson.time-zone: Asia/Singapore

jwt:
  secret: 8665ebcb30adc07590ae3209e8cb0c2b9b43762cf6656d95ddb52fbc2a45e39c
  expiry: 86400000 # 1 day

stripe:
  public-key: pk_test_51QiX7rQbT5FU30ph0CYalkohjvjzBD6FvHnqzA9WsEtCD0uQjAKZ5bIvmdWGSTgfhoSFUUSNnNHtaosoQcWinY3900OXlIy73I
  secret-key: sk_test_51QiX7rQbT5FU30phDCHtCQqXqyuwq2ihbTS6KXNmbbXRKlb1sXaUdu2YHvvLxu594GCDzwYGBDBhuVvzy1yOdSQF00mdCdRHWb